-- ============================================
-- TraceIt - PostgreSQL Database Schema
-- ============================================

-- USERS
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT users_role_check
        CHECK (role IN ('user', 'admin'))
);


-- FITNESS GOALS
CREATE TABLE IF NOT EXISTS fitness_goals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    age INTEGER NOT NULL,
    sex VARCHAR(10) NOT NULL,
    activity_level VARCHAR(30) NOT NULL,
    height_cm DECIMAL(5,2) NOT NULL,
    starting_weight DECIMAL(5,2) NOT NULL,
    target_weight DECIMAL(5,2) NOT NULL,
    daily_calorie_target INTEGER NOT NULL,
    daily_protein_target DECIMAL(6,2) NOT NULL,
    daily_fat_target DECIMAL(6,2) NOT NULL DEFAULT 0,
    daily_carb_target DECIMAL(6,2) NOT NULL DEFAULT 0,
    goal_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fitness_goals_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fitness_goals_sex_check
        CHECK (sex IN ('male', 'female'))
);


-- DAILY PROGRESS
CREATE TABLE IF NOT EXISTS daily_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    date DATE NOT NULL,
    weight_kg DECIMAL(5,2) NOT NULL,
    bmi DECIMAL(4,2),
    water_liters DECIMAL(4,2) DEFAULT 0,
    sleep_hours DECIMAL(4,2) DEFAULT 0,
    steps INTEGER DEFAULT 0,
    waist_cm DECIMAL(5,2),
    chest_cm DECIMAL(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT daily_progress_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT unique_user_progress_date
        UNIQUE (user_id, date)
);


-- FOOD LOGS
CREATE TABLE IF NOT EXISTS food_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    date DATE NOT NULL,
    food_name VARCHAR(150) NOT NULL,
    quantity_g DECIMAL(7,2) NOT NULL DEFAULT 0,
    calories INTEGER NOT NULL,
    carbs_g DECIMAL(7,2) NOT NULL DEFAULT 0,
    protein_g DECIMAL(6,2) NOT NULL,
    fat_g DECIMAL(7,2) NOT NULL DEFAULT 0,
    fiber_g DECIMAL(7,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT food_logs_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


-- WORKOUTS
CREATE TABLE IF NOT EXISTS workouts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    workout_date DATE NOT NULL,
    workout_name VARCHAR(100) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT workouts_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


-- EXERCISES
CREATE TABLE IF NOT EXISTS exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id INTEGER NOT NULL,
    exercise_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT exercises_workout_fk
        FOREIGN KEY (workout_id)
        REFERENCES workouts(id)
        ON DELETE CASCADE
);


-- EXERCISE SETS
CREATE TABLE IF NOT EXISTS exercise_sets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id INTEGER NOT NULL,
    set_number INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight_kg DECIMAL(6,2) NOT NULL,

    CONSTRAINT exercise_sets_exercise_fk
        FOREIGN KEY (exercise_id)
        REFERENCES exercises(id)
        ON DELETE CASCADE
);
